/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val p1 = Products(1, "Notebook", "Laptop de 15 pulgadas", 1200.0, 10, Category.ELECTRONICS)
    val p2 = Products(2, "Camisa", "Camisa de algodón", 25.0, 50, Category.CLOTHING)

    println(p1)
    println(p2)
  
}
