/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example


class Inventory {

    private val products: MutableList<Products> = mutableListOf()

    fun addProduct(product: Products) {
        products.add(product)
        println("Producto agregado: ${product.name}")
    }

    fun deleteProduct(idProduct: Int) {
        val deleted = products.removeIf { it.id == idProduct }
        if (deleted) {
            println("Producto con ID $idProduct eliminado.")
        } else {
            println("Producto con ID $idProduct no encontrado.")
        }
    }

    fun searchProduct(idProduct: Int): Products? {
        return products.find { it.id == idProduct }
    }

    fun showInventory() {
        if (products.isEmpty()) {
            println("El inventario está vacío.")
        } else {
            println("Inventario actual:")
            products.forEach { println(it) }
        }
    }
}
